#!/usr/bin/env bash
in="$1"
html="${1%md}html"
pdf="${1%md}pdf"

genHTML() {
	cat << EOF
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8"/>
		<style>
			html,body{
				margin-left: auto;
				margin-right: auto;
				font-size: 24px;
			}
			table {
				border-collapse: collapse;
			}
			th, td {
				border: 1px solid;
				padding: 4px;
			}
			code {
				font-family: "Iosevka";
			}
		</style>
	</head>
	<body>
EOF
	# custom replacements:
	# [BREAK] = page break
	# trailing \ = line break (two spaces in markdown)
	sed '
		s|^\[BREAK\]$|<div style="page-break-before: always;"></div>|;
		s|\\$|  |;
	' "$in" \
	| markdown_py \
		-x fenced_code -x tables -x codehilite -x toc
	cat << EOF
	</body>
</html>
EOF
}

gen() {
	genHTML > "$html"
	wkhtmltopdf --enable-local-file-access "$html" "$pdf"
}

gen
(($# == 1)) && {
	tmp="$(mktemp)"
	coproc _ (zathura "$pdf"; rm "$tmp")
	while inotifywait -e modify "$1" "$tmp"; do
		[ ! -f "$tmp" ] && break
		gen
	done
}
